# Site settings
title: Lastoblog
email: kirill.lastovirya@gmail.com  
description: > # 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://lastoblog.github.io" # gh-pages is production
twitter_username: kirhgoff
github_username:  kirhgoff

# Build settings
encoding: utf-8
highlighter: pygments
markdown: kramdown 
